### ISSUE TITLE
memmem function missing on windows.

### ISSUE THREAD

**Issue by TRANTUAN-PC** [plooshi/KPlooshFinder#6]
here are some memmem examples to modify the code.
[memmem examples.txt](https://github.com/plooshi/KPlooshFinder/files/14110960/memmem.examples.txt)

**Comment by mast3rz3ro** [comment]
Hi,

If you can compile latest clang under MSYS2/Cygwin then maybe you will be able to compile it and run it without memmem function errors.

For more info about this, please refer to this issue [here](https://github.com/msys2/MSYS2-packages/issues/4316).
